services:
  app:
    image: chatsql_app
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true
    container_name: chatsql_app
  mysql:
    image: docker.io/library/mysql:9.6.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD=toor
    container_name: mysql
